¶ work-around for https://github.com/lampepfl/dotty/issues/10665
- now basically all but Compiler is available in Dotty
- but we see a new crash:

```
java.lang.AbstractMethodError: Receiver class de.sciss.proc.impl.AuralOutputAttribute$ does not define or inherit an implementation of the resolved method 'abstract de.sciss.proc.AuralAttribute apply(java.lang.String, de.sciss.lucre.Obj, de.sciss.proc.AuralAttribute$Observer, de.sciss.lucre.synth.Txn, de.sciss.proc.AuralContext)' of interface de.sciss.proc.AuralAttribute$Factory.
        at de.sciss.proc.impl.AuralAttributeImpl$.apply(AuralAttributeImpl.scala:47)
	at de.sciss.proc.AuralAttribute$.apply(AuralAttribute.scala:27)
	at de.sciss.proc.impl.AuralProcImpl$Impl.mkAuralAttribute$$anonfun$1(AuralProcImpl.scala:396)
	at scala.Option.getOrElse(Option.scala:201)
	at de.sciss.proc.impl.AuralProcImpl$Impl.mkAuralAttribute(AuralProcImpl.scala:400)
	at de.sciss.proc.impl.AuralProcImpl$Impl.attrAdded(AuralProcImpl.scala:230)
	at de.sciss.proc.impl.AuralProcImpl$Impl.init$$anonfun$5$$anonfun$1$$anonfun$1(AuralProcImpl.scala:157)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at dotty.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at de.sciss.proc.impl.AuralProcImpl$Impl.init$$anonfun$6$$anonfun$2(AuralProcImpl.scala:161)
```